name: Anime
description: "You can request an anime by filling out the form!"
title: "[Anime]: "
labels: ["Anime"]
assignees:
  - futurkk
body:
  - type: markdown
    id: Welcome
    attributes:
      value: |
        感谢使用Texon's Emby!
  - type: input
    id: name
    attributes:
      label: 您想看动漫的名字/译名？
      placeholder: ex. 妖精的尾巴
    validations:
      required: true
  - type: input
    id: releasedate
    attributes:
      label: 这部动漫的上映时间？
      placeholder: ex. 2009
    validations:
      required: true
  - type: input
    id: TMDBurl
    attributes:
      label: 这部动漫的TMDB链接？
      placeholder: ex. https://www.themoviedb.org/tv/46261-fairy-tail
    validations:
      required: true
  - type: dropdown
    id: Countries
    attributes:
      label: 这部动漫的国家？
      options:
        - China/Hong Kong/Macao/Taiwan
        - Japan
        - Korea
        - United States/Europe
        - Others
    validations:
      required: true
